### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [timholy/PositiveFactorizations.jl#4]
The tests have deprecation warnings on the release, but they are fine on master. Could you please tag a new release?

**Comment by timholy** [comment]
Beat you to it by 2 hours (good timing!): https://github.com/JuliaLang/METADATA.jl/pull/5732.

Just waiting a bit to give folks time to review it and make sure it seems OK.

**Comment by ranjanan** [comment]
Haha, I forgot to check the METADATA PRs. Thank you!
